### ISSUE TITLE
ENHANCEMENT: C++

### ISSUE THREAD

**Issue by X-Developer-Studios** [whippingdot/Language-Tutorials#25]
In the C++ tutorial, I would recommend adding "using namespace std" so you can display output by typing "court << "output""

**Comment by thequackyduck** [comment]
you could create a pr?

**Comment by X-Developer-Studios** [comment]
I don't know how to create one lol

**Comment by Tr1angular** [comment]
You need to fork the repo and then edit and then click contribute. Once,
you do that, you need to explain what it is and then click 'Create pull
request'. Hope this helps.

**Comment by X-Developer-Studios** [comment]
@Tr1angular Thanks!

**Comment by X-Developer-Studios** [comment]
@Tr1angular Thanks!

**Comment by whippingdot** [comment]
Hey, some people recommended not using 'using namespace std;' cause they don't prefer it. The reason why is because it imports lots of functions you don't need, meaning that when you create a function the name might be the same as one the namespace imported therefore creating confusion and asking yourself why your function isn't working.

I started following this, but you don't have to. Just note - we will not include that in the tutorial. I think I already gave a shorter version of this explanation in the file...
